aug_method: all
basic_weight_decay: 0
class_num: 3
clean_count: 0.9
cls_emb_dim: 8
cnn_drop_out: 0.3
cola_score_interval: -1,1.5
cpus_per_trail: 1
cpus_per_trial: 1
epochs: 15
eval_batch_size: 8
gpus_per_trial: 1
is_debug: false
is_debug_label_flip: false
is_deeper_weight: false
is_kstep_meta: true
kernel_num: 100
kernel_sizes: 3,4,5
max_length: 128
meta_weight_decay: 0
model_name: meta_model
pre_train_meta_epochs: 0
random_seed: 123
read_score_interval: -1000,1000
train_batch_size: 4
train_count: -1
is_score_embed: false
is_contrastive_learning: true
is_sample_aligned: true
no_aug_data: false
momentum: 0.99
is_feature_normalized: true
base_temperature: 1
is_supervised_contrast: false
is_time_prior: false
queue_exclusive: false
is_weight_contrast: true
sc_include_aug: false
ttu: 300
pos_ratio: 0.9
lambda_intra_contrast: 1
is_roberta: true
is_fp16: false
temperature: 1
base_path: ./Dataset
is_scheduler_noise: false
is_freeze: false
hidden_size: 256
contrast_epoch: 0
pre_train_basic_epochs: 0
contrast_patience: 5
gradient_steps: 1
grid_search:
  basic_lr_rate: [0.000005]
  meta_lr_rate: [0.0003, 0.0005, 0.0007]
  lambda_inner_contrast: [0.05, 0.07, 0.1, 0.3, 0.5]
  gw_hidden_dim: [32]
  gw_dropout: [0.2]
  num_neg: [4096]



